---
"on":
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build:
    strategy:
      matrix:
        os:
          - "windows-11-arm"  # arm64
          - "windows-2025"    # x64
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Install uv
        run: |
          python -m pip install uv
      - name: Install Nuitka
        run: |
          uv --no-progress venv
          uv --no-progress pip install "nuitka == 2.7"

      - name: nuitka --version
        run: |
          uv --no-progress run --frozen -- nuitka --version

      - name: Build binary
        run: >
          uv --no-progress run --frozen -- nuitka --verbose
          --onefile --assume-yes-for-downloads --output-filename=my-cli-${{ matrix.os }}
          my_cli/__main__.py

      - name: Run binary
        run: |
          ./my-cli-${{ matrix.os }}.exe

      - name: Install exiftool
        run: |
          choco install exiftool --no-progress --yes

      - name: Binary metadata
        run: |
          exiftool.exe my-cli-${{ matrix.os }}.exe
